name: Linter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install pre-commit hooks
      run: |
        pip install pre-commit
        pre-commit install --install-hooks

    - name: Code style check via pre-commit
      run: |
        pre-commit run --all-files
